- hosts: localhost
  tasks:
  - name: Find host1 IPv4 address
    shell: tfctl.sh --provider aws --module syslog-ha --action output --qualifier host1_ip --env {{ env }}
    register: host1_ip
  - debug:
     var: host1_ip.stdout
  - name: Find host2 IPv4 address
    shell: tfctl.sh --provider aws --module syslog-ha --action output --qualifier host2_ip --env {{ env }}
    register: host2_ip
  - debug:
     var: host2_ip.stdout
  - name: Find vip
    shell: tfctl.sh --provider aws --module syslog-ha --action output --qualifier vip --env {{ env }}
    register: vip
  - debug:
     var: vip.stdout
  - name: Find region
    shell: tfctl.sh --provider aws --module network --action output --qualifier region --env {{ env }}
    register: region
  - debug:
     var: region.stdout
  - name: Find the HA monitor role for RBAC
    shell: tfctl.sh --provider aws --module iam --action output --qualifier ha_monitor_role_arn --env {{ env }}
    register: ha_monitor_role_arn
  - debug:
     var: ha_monitor_role_arn.stdout

- hosts: "{{ env | default('dev')}}-syslog-ha1, {{ env | default('dev')}}-syslog-ha2"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
  tasks:
   - include_tasks: include-aws.yaml
     vars:
      profile:  "ha-monitor"
      region:   "{{ hostvars['localhost']['region']['stdout'] }}"
      role_arn: "{{ hostvars['localhost']['ha_monitor_role_arn']['stdout'] }}"

- hosts: "{{ env | default('dev')}}-syslog-ha1"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
  tasks:
   - include_tasks: include-keepalived.yaml
     vars:
      priority: "101"
      host_ip:  "{{ hostvars['localhost']['host1_ip']['stdout'] }}"
      peer_ip:  "{{ hostvars['localhost']['host2_ip']['stdout'] }}"
      vip:      "{{ hostvars['localhost']['vip']['stdout'] }}"

- hosts: "{{ env | default('dev')}}-syslog-ha2"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
  tasks:
   - include_tasks: include-keepalived.yaml
     vars:
      priority: "100"
      host_ip:  "{{ hostvars['localhost']['host2_ip']['stdout'] }}"
      peer_ip:  "{{ hostvars['localhost']['host1_ip']['stdout'] }}"
      vip:      "{{ hostvars['localhost']['vip']['stdout'] }}"

- name: Run the syslog playbook
  import_playbook: "{{ lookup('env', 'IAC_HOME') }}/ansible/syslog/playbook.yaml"