#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
DAEMON=rsyslog
STATEFILE=/var/run/$DAEMON-ha-keepalived.state
if [ -s "$STATEFILE" ]; then
    . "$STATEFILE"
    case "$STATE" in
        "BACKUP"|"MASTER"|"FAULT")
                service $DAEMON status
                exit $?
                ;;
        *|"")
                logger -t $DAEMON-ha-keepalived "Unknown state: '$STATE'"
                exit 1
                ;;
    esac
fi

service $DAEMON status
exit $?